### ISSUE TITLE
compatibility with recent meteor version

### ISSUE THREAD

**Issue by antislash21** [MeXaaR/mdt#1]
Package is currently not compatible with meteor >= 2.3 (due to major updates on meteor accounts packages).

This can be fixed by changing the following code in package.js (tested on meteor 2.4) :

api.versionsFrom('1.9')  ->   api.versionsFrom(['1.9', '2.3']);

Thanks

**Comment by MeXaaR** [comment]
Sorry for the delay.

Package updated

**Comment by antislash21** [comment]
Thanks
